name: Run Tests

on:
  # On push
  push:
    branches: [ production ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout build
      uses: actions/checkout@v3
    
    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      
    - name: Composer Setup
      uses: php-actions/composer@v6
      with:
        dev: yes
        php_version: "7.4"
        version: latest
        command: update
        
    - name: Run Tests
      run: composer phpcs
